# Generated by Django 4.0.6 on 2022-07-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
