# Generated by Django 4.0.6 on 2022-07-27 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_comment_status_question_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
    ]
