# Generated by Django 4.0.6 on 2022-07-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_comment_rating_comment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='marks',
            field=models.BooleanField(default=False),
        ),
    ]
