# Generated by Django 4.0.6 on 2022-07-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_comment_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг комментария'),
        ),
    ]
